<?php

	$_helper = $this->helper('MageGuide\Skroutz\Helper\Data');
    $isActive = $_helper->getIsActive();
    $programID = $_helper->getProgramID();
	
	if ($isActive && $programID != ""):
?>

<!-- SKROUTZ ANALYTICS CODE start -->
<script>
  (function(a,b,c,d,e,f,g){a[e]= a[e] || function(){
    (a[e].q = a[e].q || []).push(arguments);};f=b.createElement(c);f.async=true;
    f.src=d;g=b.getElementsByTagName(c)[0];g.parentNode.insertBefore(f,g);
  })(window,document,'script','https://analytics.skroutz.gr/analytics.min.js','sa');

  sa('session', 'connect', '<?php echo $programID; ?>');  // Connect your Account.
</script>
<!-- SKROUTZ ANALYTICS CODE end -->

<?php endif; ?>